# nginx default server configuration

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    location / {
        default_type text/plain;
        return 200 'This is a private server of Qingtian Zhou. You should use a domain name to locate relevant resources.';
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;
    ssl_certificate /etc/letsencrypt/live/origin.dns.name/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/origin.dns.name/privkey.pem;
    location / {
        default_type text/plain;
        return 200 'This is a private server of Qingtian Zhou. You should use a domain name to locate relevant resources.';
    }
}
